name: Update

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:      # 支持手动触发
    
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Kdwkakcs/pwcd
          token: ${{ secrets.privates }}
          path: pwcd
        
      - name: Collect Node
        run: |
          cd pwcd
          chmod +x run_bblot.sh
          bash run_bblot.sh
        
      - name: Commit and push changes
        run: |
          cd pwcd
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update at $(date +'%Y-%m-%d %H:%M:%S')" 
          git push origin main
        